// Generated by CoffeeScript 1.6.1
(function() {
  var Bla;

  Bla = (function() {

    function Bla() {}

    Bla.prototype.test = function() {
      return console.log('hello');
    };

    Bla.prototype.tasks = [test];

    Bla.prototype.other = {
      tasks: [test]
    };

    return Bla;

  })();

}).call(this);
